# Generated by Django 4.2.30 on 2026-07-02 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_protection', '0024_project_management_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='benefitplan',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='benefitplan',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='benefitplan',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='benefitplan',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='benefitplandatauploadrecords',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='benefitplandatauploadrecords',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='groupbeneficiary',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='groupbeneficiary',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='groupbeneficiary',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='groupbeneficiary',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbenefitplan',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbenefitplan',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbenefitplan',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalbenefitplan',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbenefitplandatauploadrecords',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbenefitplandatauploadrecords',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgroupbeneficiary',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgroupbeneficiary',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgroupbeneficiary',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalgroupbeneficiary',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
    ]
